In [1]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =pd.read_csv(r"D:\IMARTICUS\Capstone Project I\data_raw\maven air line\airline_passenger_satisfaction.csv")

In [3]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  object
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  object
 4   Type of Travel                          129880 non-null  object
 5   Class                                   129880 non-null  object
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [5]:
df.shape

(129880, 24)

In [6]:
df.isnull().sum()

ID                                          0
Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

In [7]:
df['Satisfaction'].unique()

array(['Neutral or Dissatisfied', 'Satisfied'], dtype=object)

In [8]:
df['Type of Travel'].unique()

array(['Business', 'Personal'], dtype=object)

In [9]:
df['Class'].unique()

array(['Business', 'Economy', 'Economy Plus'], dtype=object)

In [21]:
df['Class'].value_counts()

Class
Business        62160
Economy         58309
Economy Plus     9411
Name: count, dtype: int64

In [10]:
df.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,64940.500000,39.427957,1190.316392,14.713713,15.091129,3.057599,2.756876,3.306267,3.252633,2.976925,3.383023,3.441361,3.350878,3.286326,3.204774,3.642193,2.728696,3.358077,3.632114
std,37493.270818,15.119360,997.452477,38.071126,38.465650,1.526741,1.401740,1.266185,1.350719,1.278520,1.287099,1.319289,1.316252,1.313682,1.329933,1.176669,1.329340,1.334049,1.180025
min,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,32470.750000,27.000000,414.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,64940.500000,40.000000,844.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,97410.250000,51.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,129880.000000,85.000000,4983.000000,1592.000000,1584.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [11]:
rating_cols = [
    'Departure and Arrival Time Convenience',
    'Ease of Online Booking',
    'Check-in Service',
    'Online Boarding',
    'Gate Location',
    'On-board Service',
    'Seat Comfort',
    'Leg Room Service',
    'Cleanliness',
    'Food and Drink',
    'In-flight Service',
    'In-flight Wifi Service',
    'In-flight Entertainment',
    'Baggage Handling'
]


df[rating_cols] = df[rating_cols].replace(0, np.nan)

In [12]:
df['Arrival Delay'].fillna(df['Arrival Delay'].median(), inplace=True)

C:\Users\mujaw\AppData\Local\Temp\ipykernel_40860\598595934.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Arrival Delay'].fillna(df['Arrival Delay'].median(), inplace=True)

In [13]:

df['Age Group'] = pd.cut(
    df['Age'],
    bins = [0,24,55,100],
    labels=['Young', 'Adult', 'Senior']
)

In [14]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age Group
0,1,Male,48,First-time,Business,Business,821,2,5.0,3.0,...,5.0,2.0,5.0,5.0,5.0,3.0,5.0,5,Neutral or Dissatisfied,Adult
1,2,Female,35,Returning,Business,Business,821,26,39.0,2.0,...,4.0,5.0,5.0,3.0,5.0,2.0,5.0,5,Satisfied,Adult
2,3,Male,41,Returning,Business,Business,853,0,0.0,4.0,...,5.0,3.0,5.0,5.0,3.0,4.0,3.0,3,Satisfied,Adult
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2.0,...,5.0,5.0,4.0,4.0,5.0,2.0,5.0,5,Satisfied,Adult
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3.0,...,4.0,4.0,5.0,4.0,3.0,3.0,3.0,3,Satisfied,Adult

In [15]:

df['Delay Flag'] = np.where(df['Arrival Delay'] > 15, 'Delayed', 'On Time')

In [16]:

df['Service Quality Index'] = df [[ 'Online Boarding', 'Seat Comfort', 'Cleanliness', 'In-flight Service']].mean(axis=1)

In [17]:
df.isna().sum()

ID                                           0
Gender                                       0
Age                                          0
Customer Type                                0
Type of Travel                               0
Class                                        0
Flight Distance                              0
Departure Delay                              0
Arrival Delay                                0
Departure and Arrival Time Convenience    6681
Ease of Online Booking                    5682
Check-in Service                             1
Online Boarding                           3080
Gate Location                                1
On-board Service                             5
Seat Comfort                                 1
Leg Room Service                           598
Cleanliness                                 14
Food and Drink                             132
In-flight Service                            5
In-flight Wifi Service                    3916
In-flight Entertainment                     18
Baggage Handling                             0
Satisfaction                                 0
Age Group                                    0
Delay Flag                                   0
Service Quality Index                        0
dtype: int64

In [18]:
df['Satisfaction'].value_counts() / len(df) * 100

Satisfaction
Neutral or Dissatisfied    56.553742
Satisfied                  43.446258
Name: count, dtype: float64

In [19]:

df.groupby('Class')['Satisfaction'].value_counts(normalize = True).unstack() * 100

Satisfaction  Neutral or Dissatisfied  Satisfied
Class
Business                    30.556628  69.443372
Economy                     81.232743  18.767257
Economy Plus                75.358623  24.641377

In [20]:
df.to_csv("airline_cleaned.csv", index=False)